#!/usr/bin/env bash

sudo apt update -y

## Install ansible
sudo apt install software-properties-common curl git
sudo add-apt-repository --yes --update ppa:ansible/ansible
sudo apt install ansible

## pull ansible
#sudo ansible-pull -U https://github.com/k-gomez/ansible.git # does not work
echo "Run the playbook like this:"
echo "\$ ansible-playbook main.yml"
