- hosts: localhost
  become: true
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519" # location of key
  pre_tasks:
    - name: update repos
      apt: update_cache=yes # update_cache=yes tells Ansible’s apt module to refresh the caches before applying whatever change is necessary (if any).
      changed_when: False
  tasks:
    #    - include: tasks/ssh.yml            # todo
    - include: tasks/core-setup.yml     
    - include: tasks/node-setup.yml     
    - include: tasks/npm-packages.yml   
    - include: tasks/zsh-setup.yml      
    - include: tasks/slack-setup.yml    
    - include: tasks/nvim-setup.yml     
    - include: tasks/dotfiles.yml       
