- name: installing stow
  apt: name=stow
  tags:
    - install
    - dotfiles
- name: cloning .dotfiles
  git:
    repo: 'git@github.com:kgbuquerin/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.config"
    recursive: yes
    clone: yes
  tags:
    - install
    - dotfiles
