- name: installing stow
  become: yes
  apt: name=stow
  tags:
    - install
    - dotfiles
- name: cloning .dotfiles
  git:
    repo: https://github.com/k-gomez/.dotfiles.git
    dest: "{{ lookup('env', 'HOME') }}/.config"
    recursive: yes
    clone: yes
    update: yes
  tags:
    - install
    - dotfiles
