- name: installing stow
  apt: name=stow
  tags:
    - install
    - dotfiles
- name: cloning .dotfiles
  git:
    repo: 'git@github.com:kgbuquerin/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    #accept_hostkey: yes
    clone: yes
    version: main
  tags:
    - install
    - dotfiles
- name: stow dotfiles
  shell: cd $HOME/.dotfiles && ./ubuntu
  tags:
    - install
    - dotfiles
