- name: install zsh requirements
  become: yes
  apt: 
    name: ['curl', 'wget', 'git']
  tags:
    - install
    - core
    - zsh
- name: install zsh
  apt: name=zsh
  tags:
    - install
    - productivity
    - dotfiles
    - zsh
    
- name: Install oh-my-zsh
  shell: 'curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh'
- name: Change shell
  shell: /bin/zsh  
  tags:
    - install
    - productivity
    - dotfiles
    - zsh
#- name: symlink for zsh-config
#  shell: ls -s ~/.config/zsh/.zshrc ~/.zshrc
#  tags:
#    - install
#    - productivity
#    - dotfiles
#    - zsh
